import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

export interface GenerateOptions {
  /** Path to the OpenAPI spec file (YAML or JSON) */
  input: string
  /** Output file path for generated TypeScript types */
  output: string
  /** Whether to include comments from the spec */
  exportType?: boolean
}

/**
 * Generates TypeScript types from an OpenAPI spec using openapi-typescript.
 */
export async function generate(options: GenerateOptions): Promise<void> {
  const { input, output, exportType = true } = options

  const inputPath = resolve(input)
  console.log(`[numen-codegen] Reading spec from: ${inputPath}`)

  // Read the spec file
  const specContent = readFileSync(inputPath, 'utf-8')

  // Parse input as URL or file path
  let ast: Awaited<ReturnType<typeof openapiTS>>
  try {
    // Try to use the file path directly
    const fileUrl = new URL(`file://${inputPath}`)
    ast = await openapiTS(fileUrl, {
      exportType,
    })
  } catch (err) {
    throw new Error(`[numen-codegen] Failed to parse OpenAPI spec: ${(err as Error).message}`)
  }

  // Convert AST to string
  const typeString = astToString(ast)

  // Add header comment
  const header = [
    '// ============================================================',
    '// AUTO-GENERATED — DO NOT EDIT MANUALLY',
    `// Generated by @numen/sdk-codegen from: ${input}`,
    `// Generated at: ${new Date().toISOString()}`,
    '// ============================================================',
    '',
    '',
  ].join('\n')

  const outputContent = header + typeString

  // Write output
  const outputPath = resolve(output)
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, outputContent, 'utf-8')

  console.log(`[numen-codegen] Types written to: ${outputPath}`)
  console.log(`[numen-codegen] ✅ Codegen complete!`)
}
